### PR TITLE
Load branch lengths

### PR DESCRIPTION
**Pull request by FinnOD**
I hope this all works! More details here.

https://github.com/aaronmussig/PhyloDM/issues/14#issuecomment-1604237501

### CODE REVIEW

**Comment by FinnOD** [comment]
Hi @aaronmussig, just bumping. Would you consider having a look at this? Thanks!

**Comment by aaronmussig** [comment]
Hi Finn, sorry for getting back to you so late. I appreciate the PR! I'm going to put it in today. I'll merge it into a development branch, do some testing and then release it.

**Comment by FinnOD** [comment]
Cheers! I had already forgotten about the project I was using this for but I hope it all works. I'm happy to help fix any issues with it.

**Comment by aaronmussig** [comment]
A whole year for me to get back to you was pretty bad, time is scarce these days. I appreciate the work you put in though, and thank you again!

**Pull request merged**
